# Generated by Django 2.2.1 on 2019-10-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_auto_20190531_2030'),
        ('notice', '0004_auto_20190524_1710'),
    ]

    operations = [
    ]
